import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import Navbar from '../components/Navbar';
import Results from '../components/Results';
import styles from '../styles/Home.module.css';
import requests from "../utils/requests";

export default function Home({results}) {
  console.log(results);
  return (
    <div className="font-sans">
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/h-logo.jpg" />
      </Head>
      
      <Header />
      <Navbar />
      <Results result={ results} />
    </div>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre || "fetchTrending";
  const request = await fetch(`
  https://api.themoviedb.org/3${requests[genre].url}
  `).then((response) => response.json());

  return {
    props: {
      results: request.results,
    },
  };
}

